---
- hosts: all
  become: true
  tasks:
  - package: name=gradle state=present
  - package: name=msmtp  state=present

- hosts: all
  become: true
  tasks:
  - copy: src=../templates/.ssh/id_rsa     dest=/root/.ssh/id_rsa     mode=600
  - copy: src=../templates/.ssh/id_rsa.pub dest=/root/.ssh/id_rsa.pub mode=644
  - template: src=../templates/msmtprc.j2 dest=/etc/msmtprc
  - copy: src=../templates/doZeMagic.sh dest=/root/doZeMagic.sh mode=+rx

- hosts: all
  become: true
  tasks:
  - git:
      repo: git@github.com:gstraymond/mtg-index-scala.git
      dest: /root/git/mtg-index-scala
      accept_hostkey: true
  - shell: gradle wrapper --gradle-version=6.1.1
    args:
      chdir: /root/git/mtg-index-scala

- hosts: all
  become: true
  tasks:
  - cron: name="job-tuesday" weekday=2 hour=23 minute=59 user="root" job="/root/doZeMagic.sh"    
  - cron: name="job-friday"  weekday=5 hour=23 minute=59 user="root" job="/root/doZeMagic.sh"    
