---
- hosts: all
  become: true
  tasks:
  - package: name=jq                   state=present
  - package: name=git                  state=present
  - package: name=default-jre-headless state=present
  - package: name=unzip                state=present

- hosts: all
  become: true
  tasks:
  - file: path=/root/.ssh                  state=directory            mode=+rx
  - file: path=/www/report/imports         state=directory            mode=+rx
  - copy: src=../templates/.ssh/id_rsa     dest=/root/.ssh/id_rsa     mode=600
  - copy: src=../templates/.ssh/id_rsa.pub dest=/root/.ssh/id_rsa.pub mode=644
  - copy: src=../templates/doZeMagic.sh    dest=/root/doZeMagic.sh    mode=+rx

- hosts: all
  become: true
  tasks:
  - git:
      repo: git@github.com:mtg-search/pics.git
      dest: /root/git/pics
      accept_hostkey: true

- hosts: all
  become: true
  tasks:
  - cron: name="job-tuesday" weekday=2 hour=23 minute=59 user="root" job="/root/doZeMagic.sh"    
  - cron: name="job-friday"  weekday=5 hour=23 minute=59 user="root" job="/root/doZeMagic.sh"    
