---
- hosts: all
  become: true
  tasks:
  - file: path=/etc/apache2 state=directory
  - copy: src=../templates/.htpasswd dest=/etc/apache2/.htpasswd
  - copy: src=../templates/options-ssl-nginx.conf dest=/etc/letsencrypt/options-ssl-nginx.conf
  - shell: openssl dhparam -out /etc/letsencrypt/dhparams.pem 2048
    args:
      creates: /etc/nginx/dhparams.pem

- hosts: all
  become: true
  roles:
    - role: jdauphant.nginx
      nginx_sites:
        tcherno:
          - listen 80
          - server_name *.tcherno.fr
          - return 301 http://tcherno.fr
        search:
          - listen 80
          - server_name search.mtg-search.com
          - error_log elasticsearch-errors.log
          - access_log elasticsearch.log
          - gzip on
          - gzip_proxied any
          - gzip_types text/plain text/css application/javascript application/xml application/json
          - location / {
              if ($request_method !~ "GET") {
                return 403;
              }
              proxy_pass http://localhost:9200;
              proxy_redirect off;
              proxy_set_header  X-Real-IP  $remote_addr;
              proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header  Host $http_host;
            }
          - listen 443 ssl
          - ssl_certificate /etc/letsencrypt/live/search.mtg-search.com/fullchain.pem
          - ssl_certificate_key /etc/letsencrypt/live/search.mtg-search.com/privkey.pem
          - include /etc/letsencrypt/options-ssl-nginx.conf
          - ssl_dhparam /etc/letsencrypt/dhparams.pem
        report:
          - listen 8080
          - server_name report.mtg-search.com
          - auth_basic "Administrator's area"
          - auth_basic_user_file /etc/apache2/.htpasswd
          - error_log web-errors.log
          - access_log web.log
          - root /www
          - location /report { autoindex on; }
